node_js:
  - 10

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: dmitrytavern/dtavern-object-parser
    - GIT_SOURCE: _docpress

script:
  - ./node_modules/.bin/docpress build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages -e; fi
